const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const gallery=[['group','Friends, fresh air and a view to remember','trail'],['camp','Your home beside the stream','camp'],['sunset','The last light of the day','sunset'],['breakfast','Slow mornings, good company','camp'],['view','A moment above the valley','trail'],['community','Adventures are better together','camp'],['bikes','Two wheels, a whole new perspective','trail'],['pool','A refreshing pause by the water','trail']];
let shown=gallery,photoIndex=0;const dialog=$('#lightbox');
function renderGallery(filter='all'){shown=gallery.filter(x=>filter==='all'||x[2]===filter);$('#gallery-grid').replaceChildren(...shown.map((item,i)=>{const b=document.createElement('button');b.className='gallery-item';b.setAttribute('aria-label',`View photo: ${item[1]}`);const img=document.createElement('img');img.src=`assets/${item[0]}.webp`;img.alt=item[1];img.loading='lazy';const caption=document.createElement('span');caption.textContent=item[1];b.append(img,caption);b.addEventListener('click',()=>{photoIndex=i;showPhoto();dialog.showModal();document.body.style.overflow='hidden'});return b}))}function showPhoto(){const item=shown[photoIndex];$('img',dialog).src=`assets/${item[0]}.webp`;$('img',dialog).alt=item[1];$('figcaption',dialog).textContent=`${item[1]} · ${photoIndex+1} / ${shown.length}`}
renderGallery();$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderGallery(b.dataset.filter)}));$('.lightbox-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.body.style.overflow='');dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});function step(n){photoIndex=(photoIndex+n+shown.length)%shown.length;showPhoto()}$('.lightbox-prev').onclick=()=>step(-1);$('.lightbox-next').onclick=()=>step(1);dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1)});
$('.menu').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open));$('.menu').setAttribute('aria-label',open?'Close navigation':'Open navigation')});$$('#navigation a').forEach(a=>a.addEventListener('click',()=>{$('#navigation').classList.remove('open');$('.menu').setAttribute('aria-expanded','false')}));
$$('[data-rate]').forEach(b=>b.addEventListener('click',()=>{$$('[data-rate]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});$$('.price').forEach(x=>x.textContent=x.dataset[b.dataset.rate]);$('[name=category]').value=b.dataset.rate==='local'?'Ugandan citizen':'International guest'}));
$$('[data-package]').forEach(a=>a.addEventListener('click',()=>{$('[name=package]').value=a.dataset.package;$('[name=guests]').value=a.dataset.package==='Couple escape'?2:1}));$('[name=package]').addEventListener('change',e=>{if(e.target.value!=='Group enquiry')$('[name=guests]').value=e.target.value==='Couple escape'?2:1});
const today=new Date();const minDate=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');$('[name=date]').min=minDate;$('#year').textContent=today.getFullYear();
$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const message=`Hello Wanale CT Campsite! I'd like to enquire about a stay.\n\nName: ${f.get('name').trim()}\nArrival: ${f.get('date')}\nNights: ${f.get('nights')}\nPackage: ${f.get('package')}\nGuests: ${f.get('guests')}\nRate category: ${f.get('category')}\nCoffee experience: ${f.has('coffee')?'Yes':'No'}\nMbale Hikers and Outdoor Club member: ${f.has('member')?'Yes':'No'}${f.get('notes').trim()?'\nNotes: '+f.get('notes').trim():''}\n\nPlease confirm availability, the total price and booking arrangements.`;window.open('https://wa.me/256702267620?text='+encodeURIComponent(message),'_blank','noopener,noreferrer')});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(el=>observer.observe(el));if(matchMedia('(hover: hover) and (pointer: fine)').matches){$$('[data-tilt]').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(1100px) rotateX(${-y*5}deg) rotateY(${x*6}deg) translateY(-3px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}}

const videoDialog=$('#video-dialog'),reelPlayer=$('#reel-player');
$$('[data-video]').forEach(card=>card.addEventListener('click',()=>{
 $$('video').forEach(video=>video.pause());
 $('#video-title').textContent=card.dataset.title;$('#video-status').textContent='';
 reelPlayer.poster=card.dataset.poster;reelPlayer.src=card.dataset.video;
 videoDialog.showModal();document.body.style.overflow='hidden';
 reelPlayer.play().catch(()=>{$('#video-status').textContent='Press play to watch this moment.'});
}));
$('.video-close').addEventListener('click',()=>videoDialog.close());
videoDialog.addEventListener('click',e=>{if(e.target===videoDialog)videoDialog.close()});
videoDialog.addEventListener('close',()=>{reelPlayer.pause();reelPlayer.removeAttribute('src');reelPlayer.load();document.body.style.overflow=''});
reelPlayer.addEventListener('error',()=>{if(reelPlayer.hasAttribute('src'))$('#video-status').textContent='This video could not load. Please check your connection and try again.'});
